[ace_world_customdm]
repo = "amoeba/ac-world-dbs"
description = "ACE World CustomDM database (CE16PY v0.7.18, CustomDM v3.14)."
version = "v0.7.18-CustomDM-v3.14"
source_url = ""

[ace_world_infiltration]
repo = "amoeba/ac-world-dbs"
description = "ACE World Infiltration database (CE16PY v0.7.18, Infiltration v0.13)."
version = "v0.7.18-Infiltration-v0.13"
source_url = ""
