[ace_world_customdm]
display_name = "Dekaru CustomDM"
world_name = "Dekaru"
upstream_source = "ACE"
upstream_version = "0.7.18"
world_variant = "CustomDM"
world_version = "3.14"

[ace_world_infiltration]
display_name = "Dekaru Infiltration"
world_name = "Dekaru"
upstream_source = "ACE"
upstream_version = "0.7.18"
world_variant = "Infiltration"
world_version = "0.13"
